apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-rbd-secret
  namespace: kube-system
type: kubernetes.io/opaque
stringData:
  # Ceph user id (example: kubernetes)
  userID: "team4-k8s-csi"
  # Ceph user key (example: AQB...==)
  userKey: "AQCdgwlqMDIwKRAAO1t079BPaR/p+l7Xb9SuYw=="
