global:
  hosts:
    domain: mgmt.local
    https: false
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-plat
  ingress:
    configureCertmanager: false
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

gitlab:
  webservice:
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 1200Mi
    service:
      type: LoadBalancer
  sidekiq:
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 300m
        memory: 1200Mi
  gitlab-shell:
    replicaCount: 1
    service:
      type: LoadBalancer
  kas:
    enabled: false
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

nginx-ingress:
  enabled: false

certmanager:
  install: false
  installCRDs: false
  createIssuers: false

certmanager-issuer:
  enabled: false
  email: admin@mgmt.local

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false
