global:
  hosts:
    domain: mgmt.local
    https: false
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

gitlab:
  webservice:
    replicaCount: 1
    service:
      type: LoadBalancer
  sidekiq:
    replicaCount: 1
  gitlab-shell:
    replicaCount: 1
    service:
      type: LoadBalancer
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

nginx-ingress:
  enabled: false

certmanager:
  installCRDs: false
  createIssuers: false
  email: admin@mgmt.local

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false

nodeSelector:
  kubernetes.io/hostname: k8s-worker-plat
