apiVersion: v1
kind: Secret
metadata:
  name: flaskapp-secret
type: Opaque
stringData:
  flask-secret: "change-me-in-production"
  database-user: "root"
  database-password: "kosa1004"
  aws-access-key-id: "S3DT3X573SDWK9F0IA84"
  aws-secret-access-key: "oDhXczQ0vAnAAczd8ZaDzSySJLf2NKDRgyey4YGR"
