---
# roles/registry/tasks/main.yml

- name: Harbor 설치 디렉토리 생성
  file:
    path: /opt/harbor
    state: directory

- name: Harbor 온라인 설치파일 다운로드 (v2.10.0)
  get_url:
    url: https://github.com/goharbor/harbor/releases/download/v2.10.0/harbor-online-installer-v2.10.0.tgz
    dest: /tmp/harbor-installer.tgz

- name: 압축 해제
  unarchive:
    src: /tmp/harbor-installer.tgz
    dest: /opt/
    remote_src: yes

- name: Harbor 설정 파일 적용 (harbor.yml)
  template:
    src: harbor.yml.j2
    dest: /opt/harbor/harbor.yml

- name: Harbor 설치 스크립트 실행
  command: ./install.sh
  args:
    chdir: /opt/harbor
    creates: /opt/harbor/common/config/adminserver/config.json  # 이미 설치되었으면 건너뜀
