---
ansible_user: kosa
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_password: kosa1004

pxc_version: 8.0
pxc_root_password: Change_Me_Secure_Password
pxc_sst_user: sst_user
pxc_sst_password: Change_Me_SST_Password
pxc_cluster_name: pxc-cluster
pxc_first_node_ip: 172.16.30.100

proxysql_mysql_servers:
  - address: 172.16.30.100
    hostgroup_id: 0
  - address: 172.16.30.101
    hostgroup_id: 0
  - address: 172.16.30.102
    hostgroup_id: 0

proxysql_mysql_users:
  - username: admin
    password: admin
    default_hostgroup: 0