apiVersion: v1
kind: Namespace
metadata:
  name: devops
  labels:
    name: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  labels:
    name: gitea
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
