---
- import_playbook: dns.yml
- import_playbook: haproxy.yml
- import_playbook: nexus.yml
- import_playbook: minio.yml
- import_playbook: k8s.yml
- import_playbook: cicd.yml
- import_playbook: monitor.yml
# TODO: 폐쇄망 패키지 미러 구성 후 주석 해제
# - import_playbook: vault.yml
# - import_playbook: siem.yml
