apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: devops

type: Opaque                                       # 문자열, 인증 키 등 다양한 데이터를 담는 비밀번호 공간
stringData:                                        # 입력한 텍스트를 쿠버네티스가 배포 시점에 Base64 형식으로 자동 암호화
  harbor-admin-password: "Kosa1004"                # harbor 웹ui로 접속해 admin으로 로그인할 때 비밀번호 설정
  database-password: "KosaDevops2026-db"           # 시스템용, 컨테이너 이미지와 계정 정보를 저장하는 DB에 접속할 비밀번호
  core-secret: "KosaDevops2026-secret"             # 시스템용, 내부 백엔드 통신 보호용 고유 보안 키
  jobservice-secret: "KosaDevops2026-jobservice"   # 시스템용, 비동기 작업을 처리하는 모듈용 내부 보안 키
