expose:
  type: loadBalancer
  loadBalancer:
    IP: ""
  tls:
    enabled: false

externalURL: http://harbor.mgmt.local

harborAdminPassword: "kosa1004"
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: "rbd-storage"
    database:
      storageClass: "rbd-storage"
    redis:
      storageClass: "rbd-storage"
    trivy:
      storageClass: "rbd-storage"
    chartmuseum:
      storageClass: "rbd-storage"

trivy:
  enabled: true

chartmuseum:
  enabled: true

nodeSelector:
  kubernetes.io/hostname: k8s-worker-plat
