apiVersion: v2
name: gitea-deployment
description: Gitea Helm chart deployment
type: application
version: 1.0.0
appVersion: 1.22.0
dependencies:
  - name: gitea
    version: 10.6.0
    repository: "https://dl.gitea.com/charts/"
