gitea:
  namespace: gitea

  ingress:
    enabled: false

  service:
    http:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: gitea-shared
    ssh:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: gitea-shared

  persistence:
    enabled: true
    storageClass: rbd-storage
    size: 20Gi

  nodeSelector:
    kubernetes.io/hostname: k8s-worker-plat

  gitea:
    admin:
      username: gitea_admin
      password: "kosa1004"
      email: admin@mgmt.local

  postgresql:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: 17.5.0-debian-12-r10
    primary:
      persistence:
        enabled: true
        storageClass: rbd-storage

  postgresql-ha:
    enabled: false
    postgresql:
      image:
        repository: bitnamilegacy/postgresql-repmgr
        tag: 17.5.0-debian-12-r10
    pgpool:
      image:
        repository: bitnamilegacy/pgpool
        tag: 4.6.1-debian-12-r0

  valkey:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/valkey
      tag: 8.1.3-debian-12-r3
    primary:
      persistence:
        enabled: true
        storageClass: rbd-storage

  valkey-cluster:
    enabled: false
    image:
      repository: bitnamilegacy/valkey-cluster
      tag: 8.1.3-debian-12-r3
