gitea:
  admin:
    username: gitea_admin
    password: "kosa1004"
    email: admin@mgmt.local

  actions:
    enabled: true

  ingress:
    enabled: false

  service:
    http:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: gitea-shared

  persistence:
    enabled: true
    storageClass: rbd-storage
    size: 20Gi

  nodeSelector:
    kubernetes.io/hostname: k8s-worker-plat

  actRunner:
    enabled: true
    replicas: 1
    container:
      privileged: true
    registration:
      create: true
      labels:
        - "k8s:docker://node:20-bookworm"

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: rbd-storage

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: rbd-storage
