---
- name: Download ProxySQL package
  get_url:
    url: "https://github.com/sysown/proxysql/releases/download/v3.0.8/proxysql_3.0.8-ubuntu22_amd64.deb"
    dest: /tmp/proxysql.deb

- name: Install ProxySQL
  apt:
    deb: /tmp/proxysql.deb

- name: Configure ProxySQL
  template:
    src: proxysql.cnf.j2
    dest: /etc/proxysql.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart ProxySQL

- name: Start ProxySQL
  systemd:
    name: proxysql
    enabled: yes
    state: started