argo-cd:
  global:
    nodeSelector:
      kubernetes.io/hostname: k8s-worker-plat

  controller:
    replicas: 1
  server:
    replicas: 1
    extraArgs:
      - --insecure
    service:
      type: LoadBalancer
  repoServer:
    replicas: 1

  configs:
    params:
      server:
        insecure: true
