[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
internal_ip_prefix=172.16.30

[percona]
pxc-pxc-1 ansible_host=172.16.30.100 pxc_node_id=1 network=internal
pxc-pxc-2 ansible_host=172.16.30.101 pxc_node_id=2 network=internal
pxc-pxc-3 ansible_host=172.16.30.102 pxc_node_id=3 network=internal

[proxysql]
pxc-proxysql-1 ansible_host=172.16.30.103 network=internal
pxc-proxysql-2 ansible_host=172.16.30.104 network=internal

[bootstrap]
pxc-pxc-1 ansible_host=172.16.30.100 network=internal

[internal:children]
percona
proxysql

[loadbalancers:children]
proxysql

[all:children]
percona
loadbalancers