---
- name: Initialize all nodes
  hosts: all
  become: yes
  vars:
    ansible_user: kosa
    ansible_password: kosa1004
  roles:
    - common

- name: Setup ProxySQL
  hosts: proxysql
  become: yes
  roles:
    - proxysql

- name: Bootstrap first Percona node
  hosts: bootstrap
  become: yes
  roles:
    - percona
  vars:
    pxc_bootstrap: true

- name: Setup remaining Percona nodes
  hosts: percona:!bootstrap
  become: yes
  roles:
    - percona
  vars:
    pxc_bootstrap: false