---
all:
  children:
    aws:
      vars:
        ansible_python_interpreter: /usr/bin/python3
      children:
        aws_haproxy:
          hosts:
            aws-haproxy-1:
              ansible_host: "{{ vault_aws_haproxy_1_ip }}"
              ansible_user: ec2-user
              ansible_ssh_private_key_file: "{{ vault_ssh_key_path }}"
            aws-haproxy-2:
              ansible_host: "{{ vault_aws_haproxy_2_ip }}"
              ansible_user: ec2-user
              ansible_ssh_private_key_file: "{{ vault_ssh_key_path }}"