---
vault_aws_haproxy_1_ip: "3.36.54.116"
vault_aws_haproxy_2_ip: "16.184.31.34"
vault_haproxy_stats_pass: "XQSrpHBed0e1JuIN"
vault_ssh_key_path: "../../kosa-proxy-key.pem"

vault_onprem_cidr: "172.16.0.0/12"

vault_eks_ingress_ip: "WILL_BE_SET_AFTER_EKS_DEPLOY"
vault_prometheus_url: "http://172.16.30.50:9090"

vault_wireguard_client_ip: "10.100.0.2/24"
vault_vpn_server_public_key: "PLACEHOLDER_REPLACE_WITH_SERVER_PUBLIC_KEY"
vault_aws_vpn_ip: "PLACEHOLDER_REPLACE_WITH_VPN_SERVER_ENDPOINT:51820"
